// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  close: () => Promise<void>;
}

interface ArchiveVideo {
  id: string;
  title: string;
  thumbnail: string;
  duration?: string;
  views?: string;
  date?: string;
  embedUrl: string;
  pageUrl: string;
}

interface ArchiveProfileResponse {
  username: string;
  videos: ArchiveVideo[];
  currentPage: number;
  totalPages: number;
  hasMore: boolean;
}

interface Recording {
  id: string;
  username: string;
  filePath: string;
  thumbnailPath: string | null;
  startedAt: number;
  stoppedAt: number | null;
  duration: number | null;
  fileSize: number | null;
  status: 'recording' | 'completed' | 'failed';
  gender: string;
  tags: string[];
}

interface ElectronAPI {
  openExternal: (url: string) => Promise<void>;
  db: any;
  archivebate: {
    getProfile: (username: string, page?: number) => Promise<{
      success: boolean;
      data?: ArchiveProfileResponse;
      error?: string;
    }>;
    getEmbedUrl: (pageUrl: string) => Promise<{
      success: boolean;
      data?: { embedUrl: string; thumbUrl?: string };
      error?: string;
    }>;
  };
  recording: {
    start: (username: string, streamerInfo?: { gender?: string; tags?: string[] }) => Promise<{ success: boolean; recording?: Recording; error?: string }>;
    stop: (username: string) => Promise<{ success: boolean; error?: string }>;
    list: () => Promise<Recording[]>;
    active: () => Promise<{ username: string; id: string; startedAt: number; duration: number }[]>;
    delete: (id: string) => Promise<{ success: boolean; error?: string }>;
    isRecording: (username: string) => Promise<boolean>;
    getFilePath: (id: string) => Promise<string | null>;
    openFolder: (id: string) => Promise<{ success: boolean; error?: string }>;
    getStorageInfo: () => Promise<{totalDiskSpace: number; freeDiskSpace: number; recordingsSize: number; recordingsPath: string;}>;
    onEvent: (callback: (event: { type: 'started' | 'completed' | 'failed'; username: string; id: string; duration?: number; fileSize?: number; error?: string }) => void) => () => void;
  };
  system: {
    setProxy: (config: any) => Promise<{ success: boolean; error?: string }>;
    clearProxy: () => Promise<{ success: boolean; error?: string }>;
    wreqFetch: (url: string, options?: any) => Promise<{ success: boolean; data?: string; status?: number; error?: string }>;
  };
  nsfwalbum: {
    fetchPage: (page: number, query: string) => Promise<{ success: boolean; data?: string; error?: string }>;
    resolveHQ: (photoId: string) => Promise<{ success: boolean; url?: string; width?: number; height?: number; error?: string }>;
  };
  bunkr: {
    fetch: (url: string) => Promise<{ success: boolean; status?: number; data?: string; error?: string }>;
  };
  proxyPool: {
    refreshPool: () => Promise<any>;
    getStats: () => Promise<any>;
    getPool: () => Promise<any>;
    getCurrent: () => Promise<any>;
    rotate: () => Promise<any>;
    applyPoolProxy: () => Promise<any>;
    reportFailure: (proxy: any) => Promise<any>;
    reportSuccess: (proxy: any) => Promise<any>;
    startAutoRefresh: () => Promise<any>;
    stopAutoRefresh: () => Promise<any>;
    getProgress: () => Promise<any>;
    onProgress: (callback: (progress: any) => void) => () => void;
    verifyIp: () => Promise<any>;
  };
  chaturbate: {
    fetch: (urlPath: string) => Promise<{ success: boolean; data?: any; error?: string }>;
    getHlsUrl: (username: string) => Promise<{ success: boolean; url?: string; error?: string }>;
  };
}

interface JavtubeContext {
  getVideos: (page: number, sortType: string, searchQuery: string) => Promise<{ success: boolean; data: any[]; error?: string }>;
  getActresses: (page: number) => Promise<{ success: boolean; data: any[]; error?: string }>;
  getActressVideos: (id: string, page: number) => Promise<{ success: boolean; data: any; error?: string }>;
  getVideoUrl: (videoId: string) => Promise<{ success: boolean; data: { videoUrl: string }; error?: string }>;
}

declare interface Window {
  themeMode: ThemeModeContext;
  electronWindow: ElectronWindow;
  electronAPI: ElectronAPI;
  javtube: JavtubeContext;
  archivebate: {
    getProfile: (username: string, page?: number) => Promise<{
      success: boolean;
      data?: ArchiveProfileResponse;
      error?: string;
    }>;
    getEmbedUrl: (pageUrl: string) => Promise<{
      success: boolean;
      data?: { embedUrl: string; thumbUrl?: string };
      error?: string;
    }>;
  };
}
