// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  close: () => Promise<void>;
}

interface ArchiveVideo {
  id: string;
  title: string;
  thumbnail: string;
  duration?: string;
  views?: string;
  date?: string;
  embedUrl: string;
  pageUrl: string;
}

interface ArchiveProfileResponse {
  username: string;
  videos: ArchiveVideo[];
  currentPage: number;
  totalPages: number;
  hasMore: boolean;
}

interface ElectronAPI {
  openExternal: (url: string) => Promise<void>;
  db: any;
  archivebate: {
    getProfile: (username: string, page?: number) => Promise<{
      success: boolean;
      data?: ArchiveProfileResponse;
      error?: string;
    }>;
    getEmbedUrl: (pageUrl: string) => Promise<{
      success: boolean;
      data?: { embedUrl: string };
      error?: string;
    }>;
  };
}

interface JavtubeContext {
  getVideos: (page: number, sortType: string, searchQuery: string) => Promise<{ success: boolean; data: any[]; error?: string }>;
  getActresses: (page: number) => Promise<{ success: boolean; data: any[]; error?: string }>;
  getActressVideos: (id: string, page: number) => Promise<{ success: boolean; data: any; error?: string }>;
  getVideoUrl: (videoId: string) => Promise<{ success: boolean; data: { videoUrl: string }; error?: string }>;
}

declare interface Window {
  themeMode: ThemeModeContext;
  electronWindow: ElectronWindow;
  electronAPI: ElectronAPI;
  javtube: JavtubeContext;
  archivebate: {
    getProfile: (username: string, page?: number) => Promise<{
      success: boolean;
      data?: ArchiveProfileResponse;
      error?: string;
    }>;
    getEmbedUrl: (pageUrl: string) => Promise<{
      success: boolean;
      data?: { embedUrl: string };
      error?: string;
    }>;
  };
}
